export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const USER_REGISTRATION = 'USER_REGISTRATION';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_EMAIL = 'PASSWORD_RESET_EMAIL';
export const AUTH_EMAIL_QUEUE = 'AUTH_EMAIL_QUEUE';
export const USER_EMAIL_QUEUE = 'USER_EMAIL_QUEUE';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const ACCOUNT_UPDATE_NOTIFICATION = 'ACCOUNT_UPDATE_NOTIFICATION';
