export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const USER_REGISTRATION = 'USER_REGISTRATION';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_EMAIL = 'PASSWORD_RESET_EMAIL';
export const AUTH_EMAIL_QUEUE = 'AUTH_EMAIL_QUEUE';
